#%RAML 1.0 NamedExample
value:
  -  id: "1"
     firstName: "Peter"
     lastName: "Evans"
     postal: "63133"
     address: "1344 agreen"
     country: "usa"
     miles: 3
     creationDate: "2020-02-28T16:41:41.090Z"
     accountType: "personal"
  -  id: "2"
     firstName: "Hull"
     lastName: "Brian"
     postal: "43989"
     address: "6 blue"
     country: "usa"
     miles: 100
     creationDate: "2020-01-28T16:41:41.090Z"
     accountType: "Business"
  -  id: "3"
     firstName: "James"
     lastName: "Tom"
     postal: "34599"
     address: "6 black"
     country: "usa"
     miles: 150
     creationDate: "2020-01-28T16:41:41.090Z"
     accountType: "personal"