#%RAML 1.0 NamedExample
value:
   - firstName: "Sour"
     lastName: "tweeter"
     postal: "43111"
     address: "454 without id and creation date"
     country: "usa"
     miles: 6
     accountType: "personal"