#%RAML 1.0 NamedExample
value:
  -  id: "1"
     firstName: "Peter"
     lastName: "Evans"
     postal: "63133"
     address: "1344 single id with all values"
     country: "usa"
     miles: 3
     creationDate: "2020-02-28T16:41:41.090Z"
     accountType: "personal"